### ISSUE TITLE
Normal player kicked for spam in the same second as joining

### ISSUE THREAD

**Issue by ZathrasNotTheOne** [SuperSpyTX/AntiBot#7]
A regular player joined and was kicked for spam within the same second.

21:47:10 [INFO] [MCBans] NikolaiCannotDie has connected!
21:47:10 [INFO] NikolaiCannotDie [/173.95.163.47:62638] logged in with entity id 6699232 at ([earth] -714.4468736690596, 25.0, 656.8331253232733)
21:47:10 [INFO] [AntiBot] has detected minecraft spam!
21:47:10 [INFO] [MCBans] NikolaiCannotDie has disconnected!
...
21:47:18 [INFO] [MCBans] NikolaiCannotDie has connected!
21:47:18 [INFO] NikolaiCannotDie [/173.95.163.47:62647] logged in with entity id 6704434 at ([earth] -714.4468736690596, 25.0, 656.8331253232733)
...
21:47:36 [INFO] < NikolaiCannotDie> what just happened?

More details...
http://pastebin.com/dc7d0c7J

**Comment by SuperSpyTX** [comment]
Not enough logs.

Show the other players joining before this one.

**Comment by ZathrasNotTheOne** [comment]
These are all regular players on the server, except for Asmicky, who joined for the first time.

...
2012-06-26 21:30:15 [INFO] 1ParkourDude lost connection: disconnect.endOfStream
2012-06-26 21:30:15 [INFO] [MCBans] 1ParkourDude has disconnected!
2012-06-26 21:30:18 [INFO] [PLAYER_COMMAND] nate137: /near  
2012-06-26 21:30:22 [INFO] ESC[36;1m[G] ESC[37;1mESC[31;1mModerator  ep1cn00bt00bESC[36;1m: Bye for nowESC[m
2012-06-26 21:30:26 [INFO] [MCBans] 1ParkourDude has connected!
2012-06-26 21:30:26 [INFO] 1ParkourDude [/98.69.220.232:56710] logged in with entity id 6398556 at ([survival] -10.94537263307657, 67.17675927506424, 671.0129699504467)
2012-06-26 21:30:28 [INFO] Connection reset
2012-06-26 21:30:28 [INFO] ep1cn00bt00b lost connection: disconnect.quitting
2012-06-26 21:30:28 [INFO] [MCBans] ep1cn00bt00b has disconnected!
...
2012-06-26 21:31:22 [INFO] [MCBans] tfarcenim12123 has connected!
2012-06-26 21:31:22 [INFO] tfarcenim12123 [/24.44.156.232:49924] logged in with entity id 6409262 at ([survival] -65.94320661666796, 71.0, 691.9229973924527)
...
2012-06-26 21:36:27 [INFO] Connection reset
2012-06-26 21:36:27 [INFO] mrberry11 lost connection: disconnect.quitting
2012-06-26 21:36:27 [INFO] [MCBans] mrberry11 has disconnected!
...
2012-06-26 21:37:59 [INFO] [MCBans] jacktp has connected!
2012-06-26 21:38:00 [INFO] jacktp [/69.134.18.25:54878] logged in with entity id 6481285 at ([survival] 153.69999998807907, 71.0, -261.69999998807907)
...
2012-06-26 21:47:09 [INFO] [MCBans] ep1cn00bt00b has connected!
2012-06-26 21:47:09 [INFO] ep1cn00bt00b [/121.223.88.131:52064] logged in with entity id 6698205 at ([survival] -22.930219129998548, 55.0, 214.45434981410293)
2012-06-26 21:47:10 [INFO] [MCBans] NikolaiCannotDie has connected!
2012-06-26 21:47:10 [INFO] NikolaiCannotDie [/173.95.163.47:62638] logged in with entity id 6699232 at ([earth] -714.4468736690596, 25.0, 656.8331253232733)
2012-06-26 21:47:10 [INFO] ESC[37;1m[ESC[36;1mAntiBotESC[37;1m] ESC[31;1mhas detected minecraft spam!ESC[m
2012-06-26 21:47:10 [INFO] [MCBans] NikolaiCannotDie has disconnected!
...

2012-06-26 21:47:18 [INFO] [MCBans] NikolaiCannotDie has connected!
2012-06-26 21:47:18 [INFO] NikolaiCannotDie [/173.95.163.47:62647] logged in with entity id 6704434 at ([earth] -714.4468736690596, 25.0, 656.8331253232733)
...
2012-06-26 21:47:26 [INFO] [MCBans] ASmicky has connected!
2012-06-26 21:47:26 [INFO] Creating empty config: /Users/kf4wvk/Desktop/BukkitServer12/plugins/Essentials/userdata/asmicky.yml
2012-06-26 21:47:26 [INFO] ASmicky [/67.11.251.44:64910] logged in with entity id 6711977 at ([earth] -608.5, 76.62000000476837, 754.5)
...
2012-06-26 21:47:36 [SEVERE] Could not pass event PlayerChatEvent to Herochat
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:460)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:786)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:567)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:459)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.RuntimeException: Chatter (NikolaiCannotDie) not found.
        at com.dthielke.herochat.MessageHandler.handle(MessageHandler.java:81)
        at com.dthielke.herochat.HCPlayerListener.onPlayerChat(HCPlayerListener.java:19)
        at sun.reflect.GeneratedMethodAccessor213.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
        ... 11 more
2012-06-26 21:47:36 [INFO] < NikolaiCannotDie> what just happened?ESC[m

**Comment by ZathrasNotTheOne** [comment]
More data from a similar event that just occurred (false positive on spam).  The elided parts are normal chat with nothing significant or repetitive.

...
14:34:32 [INFO] [MCBans] moost3rman has connected!
14:34:32 [INFO] moost3rman [/96.232.159.247:61961] logged in with entity id 2344572 at ([survival] -1553.7455997468421, 15.0, -251.69999998807907)
14:34:32 [INFO] /50.23.30.168:39671 lost connection
...
14:35:43 [INFO] 1ParkourDude lost connection: disconnect.endOfStream
14:35:43 [INFO] [MCBans] 1ParkourDude has disconnected!
14:35:47 [INFO] [MCBans] 1ParkourDude has connected!
14:35:47 [INFO] 1ParkourDude [/98.69.220.232:50906] logged in with entity id 2356360 at ([survival] -1396.2562649894546, 63.60000002384186, -202.4436585267992)
...
14:43:30 [INFO] Read timed out
14:43:30 [INFO] 1ParkourDude lost connection: disconnect.endOfStream
14:43:30 [INFO] [MCBans] 1ParkourDude has disconnected!
14:43:42 [INFO] [MCBans] 1ParkourDude has connected!
14:43:42 [INFO] 1ParkourDude [/98.69.220.232:50937] logged in with entity id 2472164 at ([survival] -1027.7262466399668, 64.0, -23.086562634937682)
...
14:45:04 [INFO] 1ParkourDude lost connection: disconnect.quitting
14:45:04 [INFO] Connection reset
14:45:04 [INFO] [MCBans] 1ParkourDude has disconnected!
...
14:54:23 [INFO] [MCBans] Svennimatorn has connected!
14:54:23 [INFO] Svennimatorn [/85.166.72.147:49807] logged in with entity id 2706623 at ([survival] 468.50008166619347, 61.0, -1167.300000011921)
...
14:56:51 [INFO] [MCBans] Monkeyup has connected!
14:56:51 [INFO] Monkeyup [/76.3.125.34:10175] logged in with entity id 2818709 at ([earth] -295.08926284175436, 26.0, 664.2362817126822)
14:56:53 [INFO] [MCBans] 1ParkourDude has connected!
14:56:54 [INFO] 1ParkourDude [/98.69.220.232:51072] logged in with entity id 2821740 at ([survival] -64.53481180253118, 72.0, 685.380663022709)
14:56:54 [INFO] [AntiBot] has detected minecraft spam!
14:56:54 [INFO] [MCBans] 1ParkourDude has disconnected!
14:56:54 [SEVERE] Could not pass event PlayerQuitEvent to Herochat
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:460)
    at net.minecraft.server.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:179)
    at net.minecraft.server.NetServerHandler.disconnect(NetServerHandler.java:158)
    at org.bukkit.craftbukkit.entity.CraftPlayer.kickPlayer(CraftPlayer.java:213)
    at me.freebuild.superspytx.handlers.BotHandler.onPlayerJoin(BotHandler.java:195)
    at me.freebuild.superspytx.listeners.BotListener.onPlayerJoin(BotListener.java:64)
    at sun.reflect.GeneratedMethodAccessor272.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:460)
    at net.minecraft.server.ServerConfigurationManager.c(ServerConfigurationManager.java:132)
    at net.minecraft.server.NetLoginHandler.b(NetLoginHandler.java:129)
    at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:41)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:61)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:567)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:459)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NullPointerException
    at com.dthielke.herochat.YMLChatterStorage.update(YMLChatterStorage.java:87)
    at com.dthielke.herochat.YMLChatterStorage.removeChatter(YMLChatterStorage.java:70)
    at com.dthielke.herochat.ChatterManager.removeChatter(ChatterManager.java:61)
    at com.dthielke.herochat.ChatterManager.removeChatter(ChatterManager.java:72)
    at com.dthielke.herochat.HCPlayerListener.onPlayerQuit(HCPlayerListener.java:40)
    at sun.reflect.GeneratedMethodAccessor342.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
    ... 20 more

**Comment by SuperSpyTX** [comment]
Reset the configuration entirely and try again.

I want a fresh config.
